export default {
  SETUP_USER: 'SETUP_USER',
  TAKEN_JOB: 'TAKEN_JOB',
  CONFIRM_RESULT: 'CONFIRM_RESULT',
  CHECK_ALIVE: 'CHECK_ALIVE',
  BUY_ITEM: 'BUY_ITEM',
  SELL_ITEM: 'SELL_ITEM',
  MARRY: 'MARRY',
  DIVORCE: 'DIVORCE',
  DEFINE_INITIAL_JOB_STATUS: 'DEFINE_INITIAL_JOB_STATUS',
  DEFINE_INITIAL_WIFE_STATUS: 'DEFINE_INITIAL_WIFE_STATUS',
};
