export default {
  user: {
    name: 'Dude',
    pringles: 10,
    drPepper: 10,
    level: 0,
    computers: {
      1: 'purchased',
    },
    bankAccount: 100,
    pulse: 80,
    status: 'alive',
    loggedIn: false,
  },
  death: {
    1: {
      message: 'Welcome to Heaven....',
      button: 'Cool!',
    },
    2: {
      message: 'There are no bugs here, RAM is unlimited and Dr.Pepper runs right into your veins',
      button: 'Oh, Jeeeeez',
    },
    3: {
      message: 'So roll up your sleeves and get back to work',
      button: 'Okay!',
    },
  },
  loginUI: {
    1: {
      label: 'This simple Game is my QUICK JS demo :) May I know your name, please?',
      buttonOne: 'Sure!',
      buttonTwo: false,
    },
    2: {
      label: 'Thanks! Guess what!? You got hired by Tony Stark\'s Company as a young and promissing talent. Yep! That\'s right!',
      buttonOne: 'Okay!',
      buttonTwo: false,
    },
    3: {
      label: 'You got 100 bucks, wonderful Ford Ka and whole horizon of opportunities!',
      buttonOne: 'Alright!',
      buttonTwo: 'Where is Exit?',
    },
    4: {
      label: 'No-no, you have to check this out, I\'ve spent 4 days on that... Go click okay :)',
      buttonOne: 'Okay...',
      buttonTwo: false,
    },
  },
  jobs: {
    1: {
      id: 1,
      type: 'HR Department',
      requirements: 'Just some PC needed',
      requiredLevel: 0,
      requiredComputer: 1,
    },
    2: {
      id: 2,
      type: 'IT Support',
      requirements: 'Level 10 + Intel Core Duo',
      requiredLevel: 10,
      requiredComputer: 2,
    },
    3: {
      id: 3,
      type: 'SWAT',
      requirements: 'Level 25 + MacBook Pro',
      requiredLevel: 25,
      requiredComputer: 3,
    },
    4: {
      id: 4,
      type: 'Nuclear Department',
      requirements: 'Level 30 + 18 Core iMac Pro',
      requiredLevel: 40,
      requiredComputer: 4,
    },
    5: {
      id: 5,
      type: 'Aliens Department',
      requirements: 'Level 40 + Blue Gene/Q 100',
      requiredLevel: 60,
      requiredComputer: 5,
    },
    6: {
      id: 6,
      type: 'Zone K4',
      requirements: 'Level 99 + RX347-Z',
      requiredLevel: 99,
      requiredComputer: 6,
    },
  },
  food: {
    1: {
      id: 1,
      name: 'Pringles',
      price: '25',
      status: false,
    },
    2: {
      id: 2,
      name: 'Dr.Pepper',
      price: '12',
      status: false,
    },
  },
  stuff: {
    1: {
      id: 1,
      name: 'Pentium II',
      price: '50',
      status: true,
    },
    2: {
      id: 2,
      name: 'Intel Core Duo',
      price: '200',
      status: false,
    },
    3: {
      id: 3,
      name: 'MacBook Pro 15"',
      price: '2799',
      status: false,
    },
    4: {
      id: 4,
      name: 'iMac Pro 18 Core',
      price: '13926',
      status: false,
    },
    5: {
      id: 5,
      name: 'Blue Gene/Q 100 petaFLOPS',
      price: '50000000',
      status: false,
    },
    6: {
      id: 6,
      name: 'RX347-Z',
      price: '748000000000',
      status: false,
    },
  },
  cars: {
    1: {
      id: 1,
      name: 'Grandma\'s Ford KA',
      price: '50',
      status: true,
    },
    2: {
      id: 2,
      name: 'Old Volkswagen Golf',
      price: '2500',
      status: false,
    },
    3: {
      id: 3,
      name: 'Audi A4',
      price: '7500',
      status: false,
    },
    4: {
      id: 4,
      name: 'BMW 3 Series',
      price: '14550',
      status: false,
    },
    5: {
      id: 5,
      name: 'Mercedes E Class Coupe',
      price: '53000',
      status: false,
    },
    6: {
      id: 6,
      name: 'Volvo XC90',
      price: '78000',
      status: false,
    },
    7: {
      id: 7,
      name: 'Rolls Royce Phantom',
      price: '304000',
      status: false,
    },
    8: {
      id: 8,
      name: 'Bugatti Chiron',
      price: '3400000',
      status: false,
    },
    9: {
      id: 9,
      name: '1928 Bentley Thunder Guts',
      price: '10000000',
      status: false,
    },
  },
  houses: {
    1: {
      id: 1,
      name: 'Wonderful house in woods',
      price: '3',
      status: true,
    },
    2: {
      id: 2,
      name: 'Grandma\'s old house',
      price: '5000',
      status: false,
    },
    3: {
      id: 3,
      name: 'Just a house',
      price: '75000',
      status: false,
    },
    4: {
      id: 4,
      name: 'Pretty good house',
      price: '250000',
      status: false,
    },
    5: {
      id: 5,
      name: 'Ho-o-o-o-use',
      price: '450000',
      status: false,
    },
    6: {
      id: 6,
      name: 'Really damn good house',
      price: '650000',
      status: false,
    },
    7: {
      id: 7,
      name: 'Now THAT\'S a real house',
      price: '1000000',
      status: false,
    },
    8: {
      id: 8,
      name: 'Emm... House?',
      price: '1500000000',
      status: false,
    },
    9: {
      id: 9,
      name: 'House 🧐',
      price: '587000000000',
      status: false,
    },
  },
  wives: {
      1: {
        id: 1,
        name: 'Hobo with a Shotgun',
        title: 'Really Cool Hobo',
        requiredLevel: 0,
      },
      2: {
        id: 2,
        name: 'A Girl... technically',
        title: 'Really Special Wife',
        requiredLevel: 15,
      },
      3: {
        id: 3,
        name: 'An Emily Ratajkowski Girl',
        title: 'Cmon... self-explainable...',
        requiredLevel: 35,
      },
      4: {
        id: 4,
        name: 'You worked too much...',
        title: 'Seems like you worked too much',
        requiredLevel: 98,
      },
    },
};
